---
- name: Operating system dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
    - python-pip
    - python-virtualenv
    - dialog
    - ca-certificates
- name: Python cryptography module
  pip: name=cryptography
- name: Letsencrypt Python client
  git:
    dest: /opt/certbot
    clone: yes
    update: yes
    repo: https://github.com/certbot/certbot
    force: yes
    version: '{{letsencrypt_certbot_version}}'
