---
- name: Temporarily stop nginx
  service: name=nginx state=stopped 

- include: client.yaml
- include: cert.yaml

- include: test.yaml
  when: letsencrypt_test

- name: Temporarily stop nginx
  service: name=nginx state=started 
